// A Drive connection that is intentionally separate from the app's Google
// sign-in (Firebase Auth). It uses Google Identity Services' OAuth2 token
// client directly, so connecting/disconnecting Drive never touches the
// signed-in app account — the two can be different Google accounts.
//
// Requires VITE_GOOGLE_CLIENT_ID — the "Web client ID" already generated by
// Firebase under Authentication → Sign-in method → Google → Web SDK
// configuration (Google Cloud Console → APIs & Services → Credentials for
// the same project also shows it). No new OAuth app needs to be created.
//
// Multiple Google accounts can be linked at once — each keeps its own
// access token, keyed by email. One of them is "active" (the one whose
// files are shown), but all of them stay connected so copy/move can pull
// from one and push to another.

// drive.readonly alone can't create folders or upload files. drive.file
// would only let us write into files/folders this app itself created, not
// into arbitrary existing folders the person browses to — so full `drive`
// is needed to upload into any folder they navigate to in-app.
const SCOPE = 'https://www.googleapis.com/auth/drive openid email profile'
const SCOPE_VERSION = 2 // bump whenever SCOPE changes, to force existing sessions to reconnect
const ACCOUNTS_KEY = 'elite-notebook:drive-accounts'
const ACTIVE_KEY = 'elite-notebook:drive-active-account'
const LEGACY_SINGLE_KEY = 'elite-notebook:drive-session' // pre-multi-account format
const CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID

let scriptPromise = null

function loadScript() {
  if (scriptPromise) return scriptPromise
  scriptPromise = new Promise((resolve, reject) => {
    if (window.google?.accounts?.oauth2) {
      resolve()
      return
    }
    const s = document.createElement('script')
    s.src = 'https://accounts.google.com/gsi/client'
    s.async = true
    s.defer = true
    s.onload = () => resolve()
    s.onerror = () => reject(new Error('Failed to load Google Identity Services'))
    document.head.appendChild(s)
  })
  return scriptPromise
}

// Accounts are keyed by email (a Google account's email is a stable,
// natural id — and it means adding the same account twice just refreshes
// its token instead of creating a duplicate entry).
export function loadDriveAccounts() {
  try {
    const raw = localStorage.getItem(ACCOUNTS_KEY)
    if (raw) {
      const accounts = JSON.parse(raw)
      return accounts.filter((a) => a.scopeVersion === SCOPE_VERSION)
    }
    // Migrate a pre-multi-account session, if one exists.
    const legacyRaw = localStorage.getItem(LEGACY_SINGLE_KEY)
    if (legacyRaw) {
      const legacy = JSON.parse(legacyRaw)
      localStorage.removeItem(LEGACY_SINGLE_KEY)
      if (legacy.scopeVersion === SCOPE_VERSION && legacy.email) {
        saveDriveAccounts([legacy])
        return [legacy]
      }
    }
    return []
  } catch {
    return []
  }
}

export function saveDriveAccounts(accounts) {
  localStorage.setItem(ACCOUNTS_KEY, JSON.stringify(accounts))
}

export function loadActiveAccountEmail() {
  return localStorage.getItem(ACTIVE_KEY) || null
}

export function saveActiveAccountEmail(email) {
  if (email) localStorage.setItem(ACTIVE_KEY, email)
  else localStorage.removeItem(ACTIVE_KEY)
}

async function fetchEmail(accessToken) {
  try {
    const res = await fetch('https://www.googleapis.com/oauth2/v2/userinfo', {
      headers: { Authorization: `Bearer ${accessToken}` },
    })
    if (!res.ok) return null
    const data = await res.json()
    return data
  } catch {
    return null
  }
}

// interactive=true shows the account picker/consent popup.
// interactive=false tries a silent, no-popup refresh using the browser's
// existing Google session — this is what lets Drive "stay connected" after
// closing and reopening the app, without asking the person to sign in again.
// selectAccount=true forces Google's account chooser even if the browser
// already has a Google session — this is how "add another account" lets
// someone pick a *different* account than the one already linked.
export function requestDriveToken({ interactive = true, loginHint, selectAccount = false } = {}) {
  return loadScript().then(
    () =>
      new Promise((resolve, reject) => {
        if (!CLIENT_ID) {
          reject(new Error('missing-client-id'))
          return
        }
        const client = window.google.accounts.oauth2.initTokenClient({
          client_id: CLIENT_ID,
          scope: SCOPE,
          callback: async (resp) => {
            if (resp.error) {
              reject(new Error(resp.error))
              return
            }
            const profile = await fetchEmail(resp.access_token)
            const session = {
              accessToken: resp.access_token,
              expiresAt: Date.now() + (Number(resp.expires_in) || 3300) * 1000,
              email: profile?.email || loginHint || null,
              name: profile?.name || null,
              picture: profile?.picture || null,
              scopeVersion: SCOPE_VERSION,
            }
            resolve(session)
          },
          error_callback: (err) => reject(new Error(err?.type || 'popup_failed')),
        })
        client.requestAccessToken({
          prompt: selectAccount ? 'select_account consent' : interactive ? 'consent' : '',
          hint: loginHint || undefined,
        })
      })
  )
}
