// A Drive connection that is intentionally separate from the app's Google
// sign-in (Firebase Auth). It uses Google Identity Services' OAuth2 token
// client directly, so connecting/disconnecting Drive never touches the
// signed-in app account — the two can be different Google accounts.
//
// Requires VITE_GOOGLE_CLIENT_ID — the "Web client ID" already generated by
// Firebase under Authentication → Sign-in method → Google → Web SDK
// configuration (Google Cloud Console → APIs & Services → Credentials for
// the same project also shows it). No new OAuth app needs to be created.

const SCOPE = 'https://www.googleapis.com/auth/drive.readonly openid email profile'
const STORAGE_KEY = 'elite-notebook:drive-session'
const CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID

let scriptPromise = null

function loadScript() {
  if (scriptPromise) return scriptPromise
  scriptPromise = new Promise((resolve, reject) => {
    if (window.google?.accounts?.oauth2) {
      resolve()
      return
    }
    const s = document.createElement('script')
    s.src = 'https://accounts.google.com/gsi/client'
    s.async = true
    s.defer = true
    s.onload = () => resolve()
    s.onerror = () => reject(new Error('Failed to load Google Identity Services'))
    document.head.appendChild(s)
  })
  return scriptPromise
}

export function loadDriveSession() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? JSON.parse(raw) : null
  } catch {
    return null
  }
}

export function saveDriveSession(session) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(session))
}

export function clearDriveSession() {
  localStorage.removeItem(STORAGE_KEY)
}

async function fetchEmail(accessToken) {
  try {
    const res = await fetch('https://www.googleapis.com/oauth2/v2/userinfo', {
      headers: { Authorization: `Bearer ${accessToken}` },
    })
    if (!res.ok) return null
    const data = await res.json()
    return data.email || null
  } catch {
    return null
  }
}

// interactive=true shows the account picker/consent popup.
// interactive=false tries a silent, no-popup refresh using the browser's
// existing Google session — this is what lets Drive "stay connected" after
// closing and reopening the app, without asking the person to sign in again.
export function requestDriveToken({ interactive = true, loginHint } = {}) {
  return loadScript().then(
    () =>
      new Promise((resolve, reject) => {
        if (!CLIENT_ID) {
          reject(new Error('missing-client-id'))
          return
        }
        const client = window.google.accounts.oauth2.initTokenClient({
          client_id: CLIENT_ID,
          scope: SCOPE,
          callback: async (resp) => {
            if (resp.error) {
              reject(new Error(resp.error))
              return
            }
            const email = await fetchEmail(resp.access_token)
            const session = {
              accessToken: resp.access_token,
              expiresAt: Date.now() + (Number(resp.expires_in) || 3300) * 1000,
              email,
            }
            saveDriveSession(session)
            resolve(session)
          },
          error_callback: (err) => reject(new Error(err?.type || 'popup_failed')),
        })
        client.requestAccessToken({
          prompt: interactive ? 'consent' : '',
          hint: loginHint || undefined,
        })
      })
  )
}
